final touch

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -143,21 +143,12 @@ jobs:
           }' ${{ secrets.DISCORD_WEBHOOK_URL }}
 
       - name: Build Docker image
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          push: true
-          tags: |
-            abdulrhmanashraf98/marom-medical:${{ github.sha }}
-            abdulrhmanashraf98/marom-medical:latest
-          build-args: |
-            APP_PORT=${{ secrets.APP_PORT }}
-            DB_HOST=${{ secrets.DB_HOST }}
-            DB_PORT=${{ secrets.DB_PORT }}
-            DB_USERNAME=${{ secrets.DB_USERNAME }}
-            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
-            DB_DATABASE=${{ secrets.DB_DATABASE }}
-            DB_TYPE=${{ secrets.DB_TYPE }}
+        run: |
+          docker build -t abdulrhmanashraf98/marom-medical:${{ github.sha }} .
+          if [ $? -ne 0 ]; then
+            echo "Docker build failed"
+            exit 1
+          fi
 
       - name: Notify Discord of build success
         if: success()
