final touch

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -28,33 +28,36 @@ jobs:
           npm install
 
       - name: Run tests
+        id: test
         run: |
           npm test
         continue-on-error: true
 
-      - name: Notify Discord of test failure
-        if: failure()
+      - name: Notify Discord of test result
+        if: always()
         run: |
-          curl -H "Content-Type: application/json" -X POST -d '{
-            "embeds": [{
-              "title": "Test Failure",
-              "description": "Tests failed for commit `${{ github.sha }}`. Check the logs for details.",
-              "color": 16711680,
-              "thumbnail": {
-                "url": "https://example.com/failure-image.png"
-              },
-              "fields": [
-                {
-                  "name": "Commit SHA",
-                  "value": "${{ github.sha }}",
-                  "inline": true
+          if [ ${{ steps.test.outcome }} == 'failure' ]; then
+            curl -H "Content-Type: application/json" -X POST -d '{
+              "embeds": [{
+                "title": "Test Failure",
+                "description": "Tests failed for commit `${{ github.sha }}`. Check the logs for details.",
+                "color": 16711680,
+                "thumbnail": {
+                  "url": "https://example.com/failure-image.png"
+                },
+                "fields": [
+                  {
+                    "name": "Commit SHA",
+                    "value": "${{ github.sha }}",
+                    "inline": true
+                  }
+                ],
+                "footer": {
+                  "text": "GitHub Actions CI/CD"
                 }
-              ],
-              "footer": {
-                "text": "GitHub Actions CI/CD"
-              }
-            }]
-          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
+              }]
+            }' ${{ secrets.DISCORD_WEBHOOK_URL }}
+          fi
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
@@ -105,6 +108,53 @@ jobs:
             DB_DATABASE=${{ secrets.DB_DATABASE }}
             DB_TYPE=${{ secrets.DB_TYPE }}
 
+      - name: Notify Discord of build result
+        if: always()
+        run: |
+          if [ ${{ steps.build.outcome }} == 'success' ]; then
+            curl -H "Content-Type: application/json" -X POST -d '{
+              "embeds": [{
+                "title": "Build Success",
+                "description": "Build completed successfully for commit `${{ github.sha }}`.",
+                "color": 65280,
+                "thumbnail": {
+                  "url": "https://example.com/success-image.png"
+                },
+                "fields": [
+                  {
+                    "name": "Commit SHA",
+                    "value": "${{ github.sha }}",
+                    "inline": true
+                  }
+                ],
+                "footer": {
+                  "text": "GitHub Actions CI/CD"
+                }
+              }]
+            }' ${{ secrets.DISCORD_WEBHOOK_URL }}
+          else
+            curl -H "Content-Type: application/json" -X POST -d '{
+              "embeds": [{
+                "title": "Build Failure",
+                "description": "Build failed for commit `${{ github.sha }}`. Check the logs for details.",
+                "color": 16711680,
+                "thumbnail": {
+                  "url": "https://example.com/failure-image.png"
+                },
+                "fields": [
+                  {
+                    "name": "Commit SHA",
+                    "value": "${{ github.sha }}",
+                    "inline": true
+                  }
+                ],
+                "footer": {
+                  "text": "GitHub Actions CI/CD"
+                }
+              }]
+            }' ${{ secrets.DISCORD_WEBHOOK_URL }}
+          fi
+
       - name: Set up AWS CLI
         uses: aws-actions/configure-aws-credentials@v2
         with:
@@ -112,67 +162,93 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: eu-north-1
 
+      - name: Notify Discord of deployment start
+        run: |
+          curl -H "Content-Type: application/json" -X POST -d '{
+            "embeds": [{
+              "title": "Deployment Started",
+              "description": "Deployment process started for commit `${{ github.sha }}`.",
+              "color": 16776960,
+              "thumbnail": {
+                "url": "https://example.com/start-image.png"
+              },
+              "fields": [
+                {
+                  "name": "Commit SHA",
+                  "value": "${{ github.sha }}",
+                  "inline": true
+                }
+              ],
+              "footer": {
+                "text": "GitHub Actions CI/CD"
+              }
+            }]
+          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
+
       - name: Deploy to EC2
         id: deploy
         run: |
           INSTANCE_ID="${{ secrets.INSTANCE_ID }}"
-          aws ssm send-command \
+          RESPONSE=$(aws ssm send-command \
             --document-name "AWS-RunShellScript" \
             --targets "Key=instanceids,Values=$INSTANCE_ID" \
             --parameters 'commands=["docker pull abdulrhmanashraf98/marom-medical:${{ github.sha }}", "docker pull abdulrhmanashraf98/marom-medical:latest", "docker stop your-container || true", "docker rm your-container || true", "docker run -d --name your-container -p 8080:80 abdulrhmanashraf98/marom-medical:${{ github.sha }}"]' \
             --timeout-seconds 600 \
-            --region eu-north-1
-        continue-on-error: true
+            --region eu-north-1)
 
-      - name: Notify Discord of deployment failure
-        if: failure() && steps.deploy.outcome == 'failure'
+          if echo "$RESPONSE" | grep -q '"Status": "Failed"'; then
+            echo "Deployment failed"
+            exit 1
+          fi
+
+      - name: Notify Discord of deployment result
+        if: always()
         run: |
-          curl -H "Content-Type: application/json" -X POST -d '{
-            "embeds": [{
-              "title": "Deployment Failure",
-              "description": "Deployment failed for commit `${{ github.sha }}`. Check the logs for details.",
-              "color": 16711680,
-              "thumbnail": {
-                "url": "https://example.com/failure-image.png"
-              },
-              "fields": [
-                {
-                  "name": "Instance ID",
-                  "value": "${{ secrets.INSTANCE_ID }}",
-                  "inline": true
+          if [ ${{ steps.deploy.outcome }} == 'success' ]; then
+            curl -H "Content-Type: application/json" -X POST -d '{
+              "embeds": [{
+                "title": "Deployment Success",
+                "description": "Deployment completed successfully for commit `${{ github.sha }}`.",
+                "color": 65280,
+                "thumbnail": {
+                  "url": "https://example.com/success-image.png"
                 },
-                {
-                  "name": "Commit SHA",
-                  "value": "${{ github.sha }}",
-                  "inline": true
+                "fields": [
+                  {
+                    "name": "Commit SHA",
+                    "value": "${{ github.sha }}",
+                    "inline": true
+                  }
+                ],
+                "footer": {
+                  "text": "GitHub Actions CI/CD"
                 }
-              ],
-              "footer": {
-                "text": "GitHub Actions CI/CD"
-              }
-            }]
-          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
-
-      - name: Notify Discord of build and deployment success
-        if: success()
-        run: |
-          curl -H "Content-Type: application/json" -X POST -d '{
-            "embeds": [{
-              "title": "Build and Deployment Success",
-              "description": "Build and deployment completed successfully for commit `${{ github.sha }}`.",
-              "color": 65280,
-              "thumbnail": {
-                "url": "https://example.com/success-image.png"
-              },
-              "fields": [
-                {
-                  "name": "Commit SHA",
-                  "value": "${{ github.sha }}",
-                  "inline": true
+              }]
+            }' ${{ secrets.DISCORD_WEBHOOK_URL }}
+          else
+            curl -H "Content-Type: application/json" -X POST -d '{
+              "embeds": [{
+                "title": "Deployment Failure",
+                "description": "Deployment failed for commit `${{ github.sha }}`. Check the logs for details.",
+                "color": 16711680,
+                "thumbnail": {
+                  "url": "https://example.com/failure-image.png"
+                },
+                "fields": [
+                  {
+                    "name": "Instance ID",
+                    "value": "${{ secrets.INSTANCE_ID }}",
+                    "inline": true
+                  },
+                  {
+                    "name": "Commit SHA",
+                    "value": "${{ github.sha }}",
+                    "inline": true
+                  }
+                ],
+                "footer": {
+                  "text": "GitHub Actions CI/CD"
                 }
-              ],
-              "footer": {
-                "text": "GitHub Actions CI/CD"
-              }
-            }]
-          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
+              }]
+            }' ${{ secrets.DISCORD_WEBHOOK_URL }}
+          fi
